In [2]:
import numpy as np

a_matrix = np.array([[ 1,  1,  2,  3],
                    [ 4,  5,  6,  7],
                    [ 8,  9, 10, 11],
                    [12, 13, 14, 15]])

**Ejercicio 1**

In [5]:
def esCuadrada(A: np.array) -> bool:
    return A.ndim == 2 and len(A) == A[0].size

esCuadrada(a_matrix)

True

**Ejercicio 2**

In [6]:
def triangSup(A: np.array):
    return filter_matriz(A, lambda i, j: i < j)

triangSup(a_matrix)

NameError: name 'filter_matriz' is not defined

**Ejercicio 3**


In [ ]:
def triangInf(A: np.array):
    return filter_matriz(A, lambda i, j: i > j)

triangInf(a_matrix)

array([[ 0,  0,  0,  0],
       [ 4,  0,  0,  0],
       [ 8,  9,  0,  0],
       [12, 13, 14,  0]])

**Ejercicio 4**

In [11]:
def diagonal(A: np.array):
    return filter_matriz(A, lambda i, j: i == j)

diagonal(a_matrix)

array([[ 1,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

**Auxiliares ejercicios 2, 3 y 4**

In [8]:
def filter_matriz(A: np.array, condition):
    res = zerosLike(A)
    for i, row in enumerate(A):
        for j, value in enumerate(row):
            if condition(i, j):
                res[i][j] = value
    return res

def zerosLike(A: np.array):
    zerosA = A.copy()
    for a in zerosA:
        for i in range(len(a)):
            a[i] = 0
    return zerosA

**Ejercicio 5**

In [ ]:
def traza(A: np.array):
    res = 0
    for i, row in enumerate(A):
        for j, value in enumerate(row):
            if i == j:
                res += value
    return res

traza(a_matrix)

np.int64(31)

**Ejercicio 6**

In [ ]:
def traspuesta(A: np.array):
    res = zerosLike(A)
    for i, row in enumerate(A):
        for j, value in enumerate(row):
            res[i][j] = A[j][i]
            
    return res

traspuesta(a_matrix)

array([[ 1,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

**Ejercicio 7**

In [ ]:
def esSimetrica(A: np.array):
    for i, row in enumerate(A):
        for j, value in enumerate(row):
            if A[j][i] != A[i][j]:
                return False
    return True
    
esSimetrica(a_matrix)

False

**Ejercicio 8**

In [3]:
def calcularAx(A: np.array, x: np.array):
    res = np.zeros(A.shape[0])  #A.shape[0] devuelve la cantidad de filas de A
    for i, row in enumerate(A):
        for j, value in enumerate(row):
            res[i] += value * x[j] 
    return res

calcularAx(a_matrix, np.array([1,1,1,1]))
            

array([ 7., 22., 38., 54.])

**Ejercicio 9**


In [ ]:
def intercambiarFilas (A, i, j):
    copiaI = A[i].copy()
    A[i] = A[j]
    A[j] = copiaI

otro_matrix = a_matrix.copy()
intercambiarFilas(otro_matrix, 0, 1)
otro_matrix

array([[ 4,  5,  6,  7],
       [ 1,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**Ejercicio 10**

In [ ]:
def sumar_fila_multiplo(A: np.array, i: int, j: int, s: int):
    jxEscalar = A[j].copy()
    multiplicarxEscalar(s, jxEscalar)
    sumarAVector(A[i], jxEscalar)

def multiplicarxEscalar(k: int, v: np.array):
    for i in range(len(v)):
        v[i] *= k

def sumarAVector(v: np.array, u: np.array):
    for i in range(len(v)):
        v[i] += u[i]

otromas_matrix = a_matrix.copy()
sumar_fila_multiplo(otromas_matrix, 0, 1, 2)
otromas_matrix

array([[ 9, 11, 14, 17],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**Ejercicio 11**

In [ ]:
def esDiagonalmenteDominante(A: np.array):
    for i, row in enumerate(A):
        row_value = 0
        for j, value in enumerate(row):
            row_value += abs(value)
        diagonal_element = abs(A[i][i])
        if row_value - diagonal_element > diagonal_element:
            return False
    return True

diagonally_dominant_matrix = np.array([[ 312, 11, 14, 17], [ 4,  543,  6,  7], [ 8,  9, 348, 11], [12, 13, 14, 842]])
esDiagonalmenteDominante(diagonally_dominant_matrix)

True

**Ejercicio 12**

In [ ]:
def matrizCirculante(v: np.array):
    matrix = np.empty((len(v), len(v)))
    matrix[0] = v
    for i in range(1, len(v)):
        matrix[i] = siguiente_ciclo(matrix[i-1])
    return matrix

def siguiente_ciclo(v: np.array):
    res = np.empty(len(v))
    for i in range(1, len(v)):
        res[i] = v[i-1]
    res[0] = v[len(v)-1]
    return res

vector = np.array([1,2,3,4,5])
matrizCirculante(vector)        

array([[1., 2., 3., 4., 5.],
       [5., 1., 2., 3., 4.],
       [4., 5., 1., 2., 3.],
       [3., 4., 5., 1., 2.],
       [2., 3., 4., 5., 1.]])

**Ejercicio 13**

In [ ]:
def matrizVandermonde(v: np.array):
    res = np.empty((len(v), len(v)))
    for i in range (len(v)):
        res[i] = potencia_por_elemento(v, i)
    return res

def potencia_por_elemento(v: np.array, k: int):
    res = v.copy()
    for i, value in enumerate(res):
        res[i] = value ** k
    return res

matrizVandermonde(vector)    

array([[  1.,   1.,   1.,   1.,   1.],
       [  1.,   2.,   3.,   4.,   5.],
       [  1.,   4.,   9.,  16.,  25.],
       [  1.,   8.,  27.,  64., 125.],
       [  1.,  16.,  81., 256., 625.]])

**Ejercicio 14**


In [ ]:


def multiplicacion_matrices(A: np.array, M: np.array):
    res = np.empty((A.shape[0], M.shape[1]))
    n = A.shape[1]
    for i in range(len(A)):
        for j in range(M.shape[1]):
            value = 0
            for k in range(n):
                value += A[i][k] * M[k][j]
            res[i][j] = value
    return res  

def potencia_matriz(A:  np.array, k: int):
    res = A.copy()
    for _ in range(k - 1):
        res = multiplicacion_matrices(res, A)
    return res

mi_matriz = np.array([[2,2],[3,3]])
potencia_matriz(mi_matriz, 3)
    

array([[50., 50.],
       [75., 75.]])